spring:
    servlet:
        multipart:
            enabled: true #开启文件上传
            max-file-size: 10MB #限制文件上传大小为10M
    datasource:
        url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        druid:
            initial-size: 5 #连接池初始化大小
            min-idle: 10 #最小空闲连接数
            max-active: 20 #最大连接数
            web-stat-filter:
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
            stat-view-servlet: #访问监控网页的登录用户名和密码
                login-username: druid
                login-password: druid
    redis:
        host: localhost # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        lettuce:
            pool:
                max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 8 # 连接池中的最大空闲连接
                min-idle: 0 # 连接池中的最小空闲连接
            shutdown-timeout: 2000ms
        timeout: 10000ms # 连接超时时间（毫秒）

aliyun:
    oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
        accessKeyId: test # 访问身份验证中用到用户标识
        accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
        bucketName: test # oss的存储空间
        policy:
            expire: 300 # 签名有效期(S)
        maxSize: 10 # 上传文件大小(M)
        callback: http://127.0.0.1:8080/aliyun/oss/callback # 文件上传成功后的回调地址
        dir:
            prefix: blog/images/ # 上传文件夹路径前缀
        img:
            prefix: http://img.ybq87.top/ # 最后组装图片用到的前缀, 阿里云oss使用了自有域名

mybatis:
    mapper-locations:
        - classpath:dao/*.xml
        - classpath*:top/**/mapper/*.xml

redis:
    database: blog
    # 缓存的key 前缀
    key:
        admin: "ums:admin" # 管理员缓存存储地址
        permissionList: "ums:permissionList"
        authCode: "admin:authCode:" # 短信通知验证码的存储地址
    expire:
        authCode: 120 # 验证码超期时间, 单位s
        common: 86400 # 24小时

jwt:
    tokenHeader: Authorization #JWT存储的请求头
    secret: blog-secret #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24)
    tokenHead: Bearer  #JWT负载中拿到开头


## security 组件中, 配置不需要验证的url
secure:
    ignored:
        urls: #安全路径白名单
            - /doc.html
            - /swagger-ui.html
            - /swagger-resources/**
            - /swagger/**
            - /**/v2/api-docs
            - /**/*.js
            - /**/*.css
            - /**/*.png
            - /**/*.ico
            - /webjars/springfox-swagger-ui/**
            - /actuator/**
            - /druid/**
            - /admin/login
            - /admin/register
            - /admin/resetpwd

logging:
    file:
        ## 配置日志的存储位置 logback-spring.xml 会通过 ${log_path}读取此配置信息
        path: /Users/ly/Documents/workspace/logs/blog/admin

## 访问 swagger 控制
knife4j:
    basic:
        enable: true
        ## Basic认证用户名
        username: admin
        ## Basic认证密码
        password: admin