aliyun:
    oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
        accessKeyId: test # 访问身份验证中用到用户标识
        accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
        bucketName: test # oss的存储空间
        policy:
            expire: 300 # 签名有效期(S)
        maxSize: 10 # 上传文件大小(M)
        callback: http://127.0.0.1:8080/aliyun/oss/callback # 文件上传成功后的回调地址
        dir:
            prefix: blog/images/ # 上传文件夹路径前缀
        img:
            prefix: http://img.ybq87.top/ # 最后组装图片用到的前缀, 阿里云oss使用了自有域名
